spring:
  redis:
    # host: 127.0.0.1 # windows
    host: 192.168.33.100 # linux
    port: 6379
    password: #123456(home)，company is null
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
      pool:
        max-active: 20 # 连接池最大连接数
        max-wait: -1 # 最大阻塞等待时间,负值表示没有限制
        max-idle: 5 # 最大空闲连接
        min-idle: 0 # 最小空闲连接
    database: 0
    timeout: 1800000 # 连接超时时间
